music_directory     "/mnt/vault/Music"
db_file             "~/.local/share/mpd/mpd.db"
state_file          "~/.local/share/mpd/mpdstate"
playlist_directory  "~/.local/share/mpd/playlists"
log_file            "~/.local/share/mpd/mpd.log"

bind_to_address     "localhost"
port                "6600"

audio_output {
    type    "pipewire"
    name    "PipeWire"
}
