#!/bin/sh

#setwp &
#xcompmgr &
#dunst &
#unclutter &
#redshift &
#dwmbar &

export HOSTNAME="$(uname -n)"

xrdb -merge ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources
HOST_XRES="${XDG_CONFIG_HOME:-$HOME/.config}/x11/host-${HOSTNAME}.xresources"
[ -f "$HOST_XRES" ] && xrdb -merge "$HOST_XRES"
xset r rate 300 50 >/dev/null 2>&1
setxkbmap -option compose:ralt -option caps:escape >/dev/null 2>&1

case "$HOSTNAME" in
janus)
  autorandr --change --default dual
  xset -dpms
  xset s noblank
  source ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xpipewire
  deskflow &
  mpd &
  ! pidof -s protonmail-bridge >/dev/null 2>&1 &&
    setsid -f protonmail-bridge --no-window >/dev/null 2>&1
  ;;
lettera)
  source ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xpipewire
  ;;
tango)
  ! pidof -s protonmail-bridge >/dev/null 2>&1 &&
    setsid -f protonmail-bridge --no-window >/dev/null 2>&1
  ;;
*mcgill*)
  xrandr --output DP-2 --rotate left
  ;;
*)
  pidof -s runit &&
    ! pidof -s pulseaudio >/dev/null 2>&1 &&
    setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
  ;;
esac
