#!/bin/sh

#setwp &
#xcompmgr &
#dunst &
#unclutter &
#redshift &
#dwmbar &

xrdb -merge ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources
xset r rate 300 50 >/dev/null 2>&1
setxkbmap -option compose:ralt -option caps:escape >/dev/null 2>&1

case "$HOSTNAME" in
lettera|janus)
  source ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xpipewire
  ;;
*mcgill*)
  xrandr --output DP-2 --rotate left
  ;;
*)
  pidof -s runit &&
    ! pidof -s pulseaudio >/dev/null 2>&1 &&
    setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
  ;;
esac
