#!/bin/sh

# Use neovim (if installed)
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# Implicit sudo in most used commands
for bin in mount umount sv pacman su light; do
	alias $bin="sudo $bin"
done

# Verbosiyt/interactivity
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv"

# Prettify

alias \
	ls="exa --group-directories-first" \
	la="exa --group-directories-first -a" \
	ll="exa --group-directories-first -la" \
	grep="grep --color=auto" \
	diff="diff --color=auto"

# Abbreviations
alias \
	ka="killall" \
	g="git" \
	gs="git status" \
	gd="git diff" \
	ga="git add" \
	gc="git commit" \
	trem="transmission-remote" \
	sdn="sudo shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	z="zathura"

# Radian
alias r="radian"

# Mamba
alias _mamba=". /home/soffiafdz/.miniforge3/etc/profile.d/conda.sh"
