#!/bin/sh

# Use $XINITRC
[ -f "$XINITRC" ] && alias startx='startx "$XINITRC"'

case "$(uname -n)" in
Lazarus)
  alias nvim="~/.local/bin/nvim-linux-x86_64/bin/nvim"
  alias bat="batcat"
  ;;
*mcgill*)
  alias \
    _tmux="init_tmux" \
    _mamba=". /export02/data/sfernand/mamba/etc/profile.d/conda.sh" \
    _conda=". /ipl/quarantine/conda/etc/profile.d/conda.sh"
  ;;
*)
  # Check if batcat is Lazarus and/or Lettera & Tango
  alias bat="batcat"
  # Abbreviations
  alias \
    trem="transmission-remote" \
    p="sudo pacman"
  # Implicit sudo in most used commands
  for bin in mount umount sv pacman su light; do
    alias '"$bin"'='sudo "$bin"'
  done
  ;;
esac

# Use neovim (if installed) rather than vim
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Radian
alias r="radian"

# eza / exa / ls
if [ -n "$(which eza)" ]; then
  alias \
    ls='eza --color=auto --icons=auto' \
    ll='eza -lA --color=auto --icons=auto' \
    la='eza -A --color=auto --icons=auto' \
    l='eza -F --color=auto --icons=auto'
elif [ -n "$(which exa)" ]; then
  alias \
    ls="exa --group-directories-first" \
    la="exa --group-directories-first -a" \
    ll="exa --group-directories-first -la"
else
  alias \
    ls='ls --color=auto' \
    ll='ls -l --color=auto' \
    la='ls -A --color=auto' \
    l='ls -CF --color=auto'
fi

# Verbosity/interactivity
alias \
  cp="cp -iv" \
  mv="mv -iv" \
  rm="rm -vI" \
  mkd="mkdir -pv"

# Prettify
alias \
  grep="grep --color=auto" \
  diff="diff --color=auto"

# Abbreviations
alias \
  sdn="sudo shutdown -h now" \
  ka="killall" \
  g="git" \
  gs="git status" \
  gd="git diff" \
  ga="git add" \
  gc="git commit" \
  e='"$EDITOR"' \
  v='"$EDITOR"' \
  z="zathura"
