#!/bin/zsh

# Profile file; runs when logging in. Useful for Environmental/Config variables

# Adding local executables to $PATH
export PATH="$PATH:$HOME/.local/bin"

# unsetopt PROMPT_SP

# Default programs:
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="brave-beta"
export READER="zathura"
export FILE="lf"

# XDG Base Dirs
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# $HOME cleanup
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export GNUPGHOME="${XDG_CONFIG_HOME:-$HOME/.config}/gnupg"
export IPYTHONDIR="${XDG_CONFIG_HOME:-$HOME/.config}/jupyter"
export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/jupyter"
export DOCKER_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/docker"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="${XDG_CONFIG_HOME:-/.config}/java"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export TMUX_TMPDIR="XDG_RUNTIME_DIR"

# MINC-TOOLKIT-1.9.18.1
#source /opt/minc/1.9.18.1/minc-toolkit-config.sh

# Other programs
export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS=-R
#export LESS_TERMCAP_mb=$"\e[01;31m"
#export LESS_TERMCAP_md=$"\e[01;36m"
#export LESS_TERMCAP_me=$"\e[0m"
#export LESS_TERMCAP_so=$"\e[01;44;33m"
#export LESS_TERMCAP_se=$"\e[0m"
#export LESS_TERMCAP_us=$"\e[01;32m"
#export LESS_TERMCAP_ue=$"\e[0m"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export AWT_TOOLKIT="MToolkit wmname LG3D"
export _JAVA_AWT_WM_NONREPARENTING=1

[ "$HOSTNAME" = "hyde" ] \
	&& [ "$(tty)" = "/dev/tty1" ] \
	&& ! pidof -s Xorg >/dev/null 2>&1 \
	&& exec startx "$XINITRC"
