services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - "8096:8096"
      - "7359:7359/udp"
    volumes:
      - ~/.local/share/jellyfin/config:/config
      - ~/.local/share/jellyfin/cache:/cache
      - /mnt/vault/Videos/Movies:/media/movies:ro
      - /mnt/vault/Videos/TV:/media/tv:ro
      - /mnt/vault/Music:/media/music:ro
      - /mnt/vault/Calibre:/media/books:ro
      - /mnt/vault/Pictures:/media/photos:ro
    restart: unless-stopped
